### ISSUE TITLE
"As comments" vs "Like Comments"

### ISSUE THREAD

**Issue by getify** [giltayar/proposal-types-as-comments#42]
My curiosity is whether the intent or likely outcome is that JS engine parsers (and the somewhat "standardized" JS tooling world in their orbit) will treat these type annotations *as comments* or *like comments*?

What I'm getting at is, current engine ASTs (and the standard ASTs that most tools use) are very dodgy (and incomplete) on how they treat comments in JS code. You cannot, for example, parse a JS file into an AST and the re-construct that file *exactly* as it was (with any tool or AST format that I'm aware of anyway). You lose some information like whitespace in certain places, and even in the case of comments, sometimes *where* a comment was precisely is information that gets discarded/muddled when producing the AST.

So... will the same likely be true of these type annotations, in that they'll be treated as throw-away second-class citizens (the way whitespace and comments are)? Would a tool that parses a future type-annotated-JS program be unable to guarantee reliably re-producing the same source code from the AST, as was originally parsed?

Or will these type annotations likely be treated as first-class citizens in the AST, thus preserving them in their entirety (position, whitespace, inner comments, etc), so that a tool could parse as type-annotated-JS file, make a singular modification in one part of the file, and re-produce a JS file that had all the same fidelity as the original?

If they're fully realized in the AST, the JS compiler/interpreter can of course "ignore" the type-annotations later as it does its execution work. That would be far preferable, IMO, to an alternative direction -- and potential feedback from engine/tooling implementers? -- being that these type annotations are going to end up "ignored" (partly or fully) earlier during the parsing/AST stage.

**Comment by lhorie** [comment]
IMHO, this distinction seems outside the scope of the proposal, i.e. how tools choose to implement parsing is up to them. There are tools that can handle comments by using CSTs rather than ASTs, e.g. [kataw](https://github.com/kataw/kataw#printing) is one, and I believe rome.tools is looking at a similar approach. Tools like eslint make do w/ babel AST extensions.

**Comment by syg** [comment]
If these are proposed to have erasure semantics, it is highly, highly likely no parser as part of a production engine will keep AST nodes around for these. They will be scanned and discarded.

**Comment by jamiebuilds** [comment]
The proposal will inherently have to describe a grammar in order to determine when the type syntax is terminated. (This is where it differs from comments progressing until a terminator like `\n` or `*/`)

```ts
function fn(map: Map<A, B>, cb: Function) {}
                   // ^ this does not start the second parameter of `fn()`
```

But while there will need to be a grammar, there's no need for a parser to do anything but discard it. Other parsers that want to make use of the syntax can represent it however they want, there are already many different ways the same grammar gets represented.

**Comment by getify** [comment]
As far as I can tell, most of the parsers in the JS tooling world seem to take their cues from the parsers in the production engines. Since production engines have no need for whitespace or comments, JS tooling parsers use AST structures that also don't fully preserve them (or sometimes at all).

There are about a dozen different tooling interop narratives that I can imagine where JS-with-type-annotations will be strictly harder to deal with if, when passing through one tool on its way to another tool, the type-annotation stuff is lost or mangled.

I think that semantic/direction makes this feature far less interesting and compelling. But it's clear from the few replies here that there's not much interest in considering those concerns.
